version: "3"
services:
  car-service:
    container_name: car-service
    image: renanadmiral/car-service
    ports:
      - "8080"
    networks:
      - first-network
    depends_on:
      - kafka
    environment:
      - KAFKA_ADRESS=kafka:29092
      - SERVER_PORT=8080

  car-registration-service:
    container_name: car-registration-service
    image: renanadmiral/car-registration-service
    ports:
      - "8081"
    networks:
      - first-network
    depends_on:
      - kafka
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=carsLogDB
      - KAFKA_ADRESS=kafka:29092
      - WEBHOOK_SERVICE_ADRESS=http://car-service:8080
      - SERVER_PORT=8081

  gateway:
    container_name: gateway
    image: renanadmiral/gateway
    ports:
      - "9000:9000"
    networks:
      - first-network
    depends_on:
      - car-service
      - car-registration-service
    environment:
      - SPRING_PROFILES_ACTIVE=path
      - SPRING_CLOUD_GATEWAY_ROUTES[0]_ID=car-service
      - SPRING_CLOUD_GATEWAY_ROUTES[0]_URI=http://car-service:8080
      - SPRING_CLOUD_GATEWAY_ROUTES[0]_PREDICATES[0]=Path=/api/listCars, /api/createCar
      - SPRING_CLOUD_GATEWAY_ROUTES[1]_ID=car-registration-service
      - SPRING_CLOUD_GATEWAY_ROUTES[1]_URI=http://car-registration-service:8081
      - SPRING_CLOUD_GATEWAY_ROUTES[1]_PREDICATES[0]=Path=/api/logs

  mongodb:
    container_name: mongodb
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    networks:
      - first-network

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - first-network

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - first-network
networks:
  first-network:
    driver: bridge
