server:
  port: 9000
spring:
  cloud:
    gateway:
      routes:
        - id: car_service
          uri: http://localhost:8080
          predicates:
           - Path=/api/listCars, /api/createCar
        - id: registration_service
          uri: http://localhost:8081
          predicates:
           - Path=/api/logs